FROM registry.access.redhat.com/ubi9/ubi:9.7
#FROM registry.redhat.io/devspaces/udi-rhel9:3.25.0

ARG USER_HOME_DIR="/home/user"
ARG WORK_DIR="/projects"

ARG INSTALL_PACKAGES="dotnet-runtime-6.0"

ARG INSTALL_PACKAGES="procps-ng openssl git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo python3-pip python3-devel fuse-overlayfs util-linux vim-minimal vim-enhanced dotnet-hostfxr-6.0 dotnet-runtime-6.0 dotnet-sdk-6.0"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot
ENV NVM_DIR=/usr/local/nvm

COPY --chown=0:0 entrypoint.sh /

RUN set -e ; \
    dnf --disableplugin=subscription-manager install -y ${INSTALL_PACKAGES} ; \
    dnf update -y ; \
    dnf clean all ; \
    mkdir -p /usr/local/bin ; \
    mkdir -p ${WORK_DIR} ; \
    chgrp -R 0 /home ; \
    chmod -R g=u /home ${WORK_DIR} ; \
    chmod +x /entrypoint.sh ; \
    chown 0:0 /etc/passwd ; \
    chown 0:0 /etc/group ; \
    chmod g=u /etc/passwd /etc/group ; \
    # Setup for rootless podman
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    touch /etc/subgid /etc/subuid ; \
    chown 0:0 /etc/subgid ; \
    chown 0:0 /etc/subuid ; \
    chmod -R g=u /etc/subuid /etc/subgid ; \
    # Create Sym Links for OpenShift CLI (Assumed to be retrieved by an init-container)
    ln -s /projects/bin/oc /usr/local/bin/oc ; \
    ln -s /projects/bin/kubectl /usr/local/bin/kubectl

USER 0
RUN dnf -y module reset nodejs && \
    dnf -y remove nodejs npm nodejs-* && \ 
    dnf clean all && rm -rf /var/cache/dnf

RUN mkdir -p "${NVM_DIR}" ;\ 
    mkdir -p ${HOME}; \
    curl -fsSL  https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh -o /tmp/install_nvm.sh;\ 
    touch ${HOME}/.bashrc; \ 
    bash /tmp/install_nvm.sh; \ 
    rm -f /tmp/install_nvm.sh; \
    chmod -R 755 "${NVM_DIR}";

RUN printf 'export NVM_DIR="/usr/local/nvm" \n[ -s "$NVM_DIR/nvm.sh"]&& . "$NVM_DIR/nvm.sh"\n[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"\n' > /etc/profile.d/nvm.sh ;

RUN bash -lc 'source /etc/profile.d/nvm.sh && nvm install 22 && nvm alias default 22 && npm cache clean --force || true';
    
USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
